### PR TITLE
Add yarn.lock file

### PR DESCRIPTION
**Pull request by aitherios**
Add yarn.lock file for https://yarnpkg.com/

### CODE REVIEW

**Comment by Stenerson** [comment]
@aitherios Thanks for the PRs!

I hadn't heard about yarn until this. I did some quick research and it seems pretty harmless. I see that it already has a ton stars and it's a facebook project so I assume many people will be using/trying it.

I'm not opposed to adding this but I'm not really equipped to verify it at this point. Since I'm uninitiated on this, can you explain how we'll maintain this going forward? Is it as simple as running `yarn update` or something?

@thangngoc89  - your input would be helpful on this as well.

Thanks!

**Comment by Stenerson** [comment]
I've done more reading on this and feel pretty comfortable with the changes - especially because yarn will be optional for all consumers of this package. If nothing else this should speed up the examples build considerably! 😎 

I'm going to play around with this locally and hopefully merge later today.

**Comment by Stenerson** [comment]
Ok, more commentary from me...

I'm comfortable with this PR as is but I have a few thoughts. @aitherios could you comment on these to make sure I'm thinking about this correctly?

- Anyone using Yarn in their project with benefit from this, as is. Their tooling will use our `yarn.lock` file to make sure they're installing/using the correct dependencies for React-Howler and they'll be super happy.
- Other than the need for us to keep the lock file up to date when updating dependencies (using npm then yarn or just `yarn update`) this doesn't affect our dependencies or build process at all.
- Would it be worth adding an npm script that uses yarn rather than npm for the examples build?
    - My thought would be to add a script like `example:react:y` that would run `yarn` rather than `npm install`.
    - I would also leave the current `example:react` script there in-case you didn't have yarn installed and didn't want to install it to build/run the examples
    - Would this make sense? Am I taking crazy pills?

Anything else that I'm missing?

**Comment by aitherios** [comment]
You summed up pretty much everything. I could only point that it would be nice to add yarn as a devDependency.

The drawback you already mentioned, the need to change `example:react[:build]` and adding yarn to the workflow so lock files keep being used/updated.

**Comment by Stenerson** [comment]
Thanks @aitherios. I'm pretty reluctant to *require* yarn until it's widely accepted and used so I think I'll leave it off of the devDependencies for now.

We'll just have to make sure we run yarn before committing any package.json changes. I'm not very familiar with Travis - is there something I can add to the Travis config to make sure yarn.lock is updated whenever package.json is updated?

**Comment by aitherios** [comment]
@Stenerson these commits aims to address those points. Yarn was added as devDependency, lock files are synced with master and integrated on npm scripts and travis.

**Comment by Stenerson** [comment]
@aitherios Sorry this took so long to merge. I wanted to try some things locally before merging and it took me a while to get some focus time. Thanks again for the commits!

**Pull request merged**
