### PR TITLE
Update howler dependency version

### PR DESCRIPTION
**Pull request by dmednis**
Changed the howler dependency version to allow for semver patch version changes.

### CODE REVIEW

**Comment by thangngoc89** [comment]
Hey thank you for send us this PR but we are well awear of the semver and opted for a fixed versiom because even though howler.js follows semver, they usually introduced bugs in patches that break our production builds.

**Comment by dmednis** [comment]
Fixed version it is then.

**Comment by thangngoc89** [comment]
Thank you. @Stenerson could you please check if this version of howler is working fine for you? And make a new release.

**Comment by Stenerson** [comment]
Yes, I'll run a few tests (hopefully today) to make sure `2.0.6` checks out and merge this.

**Comment by Stenerson** [comment]
@dmednis let's bump to `2.0.7` since it includes a minor cosmetic fix and would get us to the most current version.

I still want to run a few tests on the stuff that was changed in `2.0.6` but we can basically get to `.7` for free so let's do it.

**Comment by thangngoc89** [comment]
@Stenerson I can add greenkeeper to the project for reminding you of newer version of howler.

**Comment by Stenerson** [comment]
Good idea @thangngoc89. 

I knew that they had a few patch releases but didn't realize that `.6` fixed a nasty deprecation warning in Chrome. They don't release too often so sticking with this plan should be manageable.

**Comment by dmednis** [comment]
Didn't notice there was a `.7` released. But yes, upgrading to the latest would be great.

**Comment by Stenerson** [comment]
`2.0.7` Seems to be working fine but there's still a deprecation warning. 
See goldfire/howler.js#856

@dmednis can you please update to `2.0.7` and run `yarn upgrade` to update (and commit) the `yarn.lock` file as well? Then I'll merge. Thanks again and be on the lookout for another bump when Howler releases a version to kill the remaining deprecation warning.

**Pull request merged**
