### PR TITLE
add `rate` prop + `.rate()` method

### PR DESCRIPTION
**Pull request by bamdadsabbagh**
Hello,

This PR adds:

- `rate` initial prop
- `.rate()` method

It is used to change the playback rate (audio speed) of sound, like you would do on a turntable.

---

sidenote: user input checking is minimal in order to have a more transparent mapping with the core library.

### CODE REVIEW

**Comment by bamdadsabbagh** [comment]
sidenote: user input checking is minimal in order to have a more transparent mapping with the core library.

**Comment by Stenerson** [comment]
Thanks @bamdadsabbagh! I think this would make for a great example. What do you think about adding a new one or adding `rate()` to the full control example?

**Comment by bamdadsabbagh** [comment]
There you go 👍🏾

**Comment by Stenerson** [comment]
Nice! 🙏 Will check this out and merge/release as soon as I can. Thanks @bamdadsabbagh!

**Comment by bamdadsabbagh** [comment]
Awesome :) Thanks a lot for your help @Stenerson !

**Comment by Stenerson** [comment]
I have to say, it's extremely fun to play with the rate in real time on the FullControl player. 👏 Nice job @bamdadsabbagh, merging now and releasing shortly.

**Comment by bamdadsabbagh** [comment]
Thanks @Stenerson ! Glad you're having fun with it (you are not the only one :P)

**Pull request merged**
