### PR TITLE
Add xhr prop

### PR DESCRIPTION
**Pull request by iakindev**
I have added xhr prop which you use when you need to stream like JWT protected content. https://github.com/goldfire/howler.js#xhr-object-null

### CODE REVIEW

**Comment by Stenerson** [comment]
Thanks @iakindev! Ahh it looks like I merged the `xhrWithCredentials` PR (#77) right after (Howler removed it)[https://github.com/goldfire/howler.js/blob/9117525f0883ddb995f99ee843bba7f6d3442590/CHANGELOG.md#220-may-17-2020] 🤦 

@andfk, not sure if you want to weigh in... 🤷‍♂️ 

I think I'll plan to merge this now and remove `xhrWithCredentials` in a future release. I don't love the duplication of `withCredentials` but it seems that the `xhr` prop allows more options that will be useful and at this point removing `xhrWithCredentials` becomes a breaking change (again 🤦)
 
I'll give it at least a day or so for people to weigh in. 🙏

**Comment by andfk** [comment]
@Stenerson 100% agree by using the `xhr` prop instead :)

Many thanks @iakindev

**Comment by iakindev** [comment]
Sounds like everybody is agreed. So I thought I might as well remove xhrWithCredentials myself.
@Stenerson, if you worried about breaking change please feel free to not include latest commit to merge.

Thanks!

**Comment by Stenerson** [comment]
Thanks @iakindev actually I think this is ok - I'll plan to cut a new major release this weekend that requires `>= 2.2.0` (the howler version that changed this functionality) and also incorporates these changes. Thanks both!

Side note: I wish Howler followed semver rather than including a known breaking change in `2.2.0` 🤷‍♂️

**Pull request merged**
