### PR TITLE
End-to-end testing

### PR DESCRIPTION
**Pull request by thangngoc89**
I'm using cypress.io for e2e testing. Currently I only test visual feedback with full control example but I think this is better then no test at all. 

Sorry for huge diff. I have prettier installed on my editor so it auto format everything I touched.

### CODE REVIEW

**Comment by Stenerson** [comment]
This will make some good new years weekend reading...
I'm not familiar with Cypress but I'll look into it to get comfortable.

Prettier is ❤️x 💯so I'm in-favor of this part too!

**Comment by thangngoc89** [comment]
@Stenerson I'm glad you're onboard with me about prettier. If the tests are passing then we're good to go.

Regarding cypress.io, it's a huge game-changer for me. E2E testing with visual feedbacks.

If you want to write test for cypress, run `npm run cypress:open` . If you want to run it in headless mode: "cypress run"

**Comment by Stenerson** [comment]
I'm vaguely familiar with Jest. Are they comparable?

**Comment by thangngoc89** [comment]
@Stenerson Oh. I use Jest everyday. They are not the same thing. Jest is a test runner, I use it for unit testing. Cypress is a end-to-end testing tool. You should clone the branch, install and `npm run cypress:open" to take a looks :D . They're totally different

**Comment by thangngoc89** [comment]
If you have an idea how to unit test React Howler, I'm up for it.

**Comment by Stenerson** [comment]
Sounds good! I'll play this weekend.

I don't think we need much test coverage here since we're really just a simple wrapper. Having some e2e tests on the examples makes sense just so we don't get an embarrassing error on the demo site. I think that's probably where you're head's at too?

**Comment by thangngoc89** [comment]
@Stenerson yep!. That's exactly what I have in mind. Also, the demo site expose pretty much everything react-howler can do so testing it ensure the functionality too

**Comment by Stenerson** [comment]
This has been sitting out here for an eternity and, let's be honest, it just ain't happening. 😂 

If someone else stumbles upon this and wants to pick it up. 👏

**Pull request closed without merging**
